
"""
This is used to just read in a solar wind time series from the evo.*.nc files generated by Enlil, as written on WCOSS
"""

import netCDF4 as nc
import seaborn as sns
import matplotlib.pyplot as plt

dt = 1.0 / (3600.0*24.0)

dir = '/home/mark.miesch/data/wsaenlil/nodd/full3D/lfs/f1/ops/prod/tmp/wsa_enlil_51507.97625337.cbqs01'

file = dir + '/evo.l1.nc'

#------------------------------------------------------------------------------
ds = nc.Dataset(file)

time = ds['TIME'][:] * dt
rho  = ds['D'][:]
T    = ds['T'][:]
x    = ds['X1'][:]
y    = ds['X2'][:]
z    = ds['X3'][:]
vx   = ds['V1'][:] * 1.e-3
vy   = ds['V2'][:] * 1.e-3
vz   = ds['V3'][:] * 1.e-3
bx   = ds['B1'][:]
by   = ds['B2'][:]
bz   = ds['B3'][:]
bp   = ds['BP'][:]

print(f"length {len(time)}")
print(f"Time range {time[0]} to {time[-1]}")

#------------------------------------------------------------------------------

fig = plt.figure(figsize = (12,8))

Tcolor = '#7F5217'
lw = 3

xrange = (-0.5, 5.0)

sns.set_theme(style={'axes.facecolor': '#FFF8DC'}, palette='colorblind')

#------------

ax1 = fig.add_subplot(2,1,1)
sns.lineplot(x = time, y = rho, color='b', linewidth = lw, ax = ax1)

#ax1.set_ylim((0.25e-20,1.75e-20))
ax1.set_ylabel('Density (g cm$^{-3}$)', fontweight = 'bold')

ax1.set_xlim(xrange)

#------------

ax2 = fig.add_subplot(2,1,2)
sns.lineplot(x = time, y = vx, color='b', linewidth = lw, ax = ax2)

#ax2.set_ylim((300,600))
ax2.set_ylabel('Velocity (km s$^{-1}$)', fontweight = 'bold')

ax2.set_xlim(xrange)
ax2.set_xlabel('time (days)', fontweight = 'bold')

#------------
fig.tight_layout(pad=1,rect=(0.01,0.01,.99,.98))

plt.show()