
"""
This is used to just read in a solar wind time series from the *.suball.nc files generated by our Enlil pipeline, as archived at NCEI.
"""

import numpy as np
import netCDF4 as nc
import seaborn as sns
import matplotlib.pyplot as plt
import datetime

dt = 1.0 / (3600.0*24.0)

#dir = '/home/mark.miesch/data/wsaenlil/ambient/20231127'
#file = dir + '/wsa_enlil.mrid00000000.suball.nc'
dir = '/home/miesch/data/wsaenlil/wcoss/AT_Alg_test'
file = dir + '/wsa_enlil.latest.suball_mrid33274.nc'
#file = dir + '/wsa_enlil.latest.suballmrid42395.nc'
#file = dir + '/wsa_enlil.latest.suballmrid51144.nc'
#file = dir + '/wsa_enlil.mrid00056864.suball.nc'
#file = dir + '/wsa_enlil.mrid00056920.suball.nc'

#------------------------------------------------------------------------------
ds = nc.Dataset(file)

# relative time in days
model_time = ds['Earth_TIME'][:] * dt

# full datetime
reftime_cal_iso = ds.getncattr('REFDATE_CAL')
t0 = datetime.datetime.fromisoformat(reftime_cal_iso)
print(f"REDATE_CAL (datetime): {t0}")
time = [t0 + datetime.timedelta(seconds=int(mt)) for mt in ds['Earth_TIME'][:]]

rho  = ds['Earth_Density'][:]
T    = ds['Earth_Temperature'][:]
x    = ds['Earth_X1'][:]
y    = ds['Earth_X2'][:]
z    = ds['Earth_X3'][:]
vx   = ds['Earth_V1'][:] * 1.e-3
vy   = ds['Earth_V2'][:] * 1.e-3
vz   = ds['Earth_V3'][:] * 1.e-3
bx   = ds['Earth_B1'][:]
by   = ds['Earth_B2'][:]
bz   = ds['Earth_B3'][:]
bp   = ds['Earth_BP_POLARITY'][:]

print("Available metadata keys:")
print(ds.variables.keys())

print("Available attributes:")
for attr in ds.ncattrs():
    print(f"{attr}: {getattr(ds, attr)}")

print(f"length {len(time)}")
print(f"Time range {time[0]} to {time[-1]}")

print(f"time = {ds['time']}")

#------------------------------------------------------------------------------

fig = plt.figure(figsize = (12,8))

Tcolor = '#7F5217'
lw = 3

#xrange = (-0.5, 5.0)

xrange = (t0 - datetime.timedelta(days=0.5), t0 + datetime.timedelta(days=5.0))

sns.set_theme(style={'axes.facecolor': '#FFF8DC'}, palette='colorblind')

#------------

ax1 = fig.add_subplot(2,1,1)
sns.lineplot(x = time, y = rho, color='b', linewidth = lw, ax = ax1)

#ax1.set_ylim((0.25e-20,1.75e-20))
ax1.set_ylabel('Density (g cm$^{-3}$)', fontweight = 'bold')

ax1.set_xlim(xrange)

#------------

ax2 = fig.add_subplot(2,1,2)
sns.lineplot(x = time, y = vx, color='b', linewidth = lw, ax = ax2)

#ax2.set_ylim((300,600))
ax2.set_ylabel('Velocity (km s$^{-1}$)', fontweight = 'bold')

ax2.set_xlim(xrange)
ax2.set_xlabel('time (days)', fontweight = 'bold')

#------------
fig.tight_layout(pad=1,rect=(0.01,0.01,.99,.98))

plt.show()